export enum ActionTypes {
  ADD_TODO = "ADD_TODO",
  TOGGLE_TODO = "TOGGLE_TODO",
  UPDATE_TODO = "UPDATE_TODO",
  LOAD_TODOS = "LOAD_TODOS",
  ADD_EVENT = "ADD_EVENT",
  UPDATE_EVENT = "UPDATE_EVENT",
  LOAD_EVENTS = "LOAD_EVENTS",
  START = "_START",
  FAIL = "_FAIL",
  SUCCESS = "_SUCCESS"
}
