// <auto-generated />
using System;
using DiaryApp.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DiaryApp.Core.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20190819164905_NewModels")]
    partial class NewModels
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DiaryApp.Core.EventModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Color");

                    b.Property<string>("Description");

                    b.Property<DateTime>("End");

                    b.Property<bool>("FullDay");

                    b.Property<int>("PageID");

                    b.Property<DateTime>("Start");

                    b.Property<string>("Subject");

                    b.Property<string>("Url");

                    b.HasKey("ID");

                    b.HasIndex("PageID");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("DiaryApp.Core.Models.FirstPage", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Month");

                    b.HasKey("ID");

                    b.ToTable("FirstPage");
                });

            modelBuilder.Entity("DiaryApp.Core.Models.TodoItem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Done");

                    b.Property<int>("PageID");

                    b.Property<int?>("PageOwnerID");

                    b.Property<string>("Subject");

                    b.HasKey("ID");

                    b.HasIndex("PageOwnerID");

                    b.ToTable("TodoItem");
                });

            modelBuilder.Entity("DiaryApp.Core.EventModel", b =>
                {
                    b.HasOne("DiaryApp.Core.Models.FirstPage", "Page")
                        .WithMany("ImportantEvents")
                        .HasForeignKey("PageID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DiaryApp.Core.Models.TodoItem", b =>
                {
                    b.HasOne("DiaryApp.Core.Models.FirstPage", "PageOwner")
                        .WithMany("ThingsTodo")
                        .HasForeignKey("PageOwnerID");
                });
#pragma warning restore 612, 618
        }
    }
}
